apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-address
spec:
  addresses:
  - 192.168.1.1
  hosts:
  - address.internal
  ports:
  - name: http
    number: 80
    protocol: HTTP