# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: web
#   annotations:
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
# spec:
#   rules:
#   - host: web-istio.app
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: web
#             port:
#               number: 80
#       - path: /admin-api
#         pathType: Exact
#         backend:
#           service:
#             name: admin-api
#             port:
#               number: 8888